# Generated by Django 5.2.7 on 2025-10-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikephoto',
            name='image',
            field=models.ImageField(upload_to='media/bike_photos/'),
        ),
    ]
